name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    name: ${{ "${{ matrix.session }} ${{ matrix.python-version }} / ${{ matrix.os }}" }}
    runs-on: ${{ "${{ matrix.os }}" }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python-version: 3.8, os: ubuntu-latest, session: "safety" }
          - { python-version: 3.8, os: ubuntu-latest, session: "mypy-3.8" }
          - { python-version: 3.7, os: ubuntu-latest, session: "mypy-3.7" }
          - { python-version: 3.6, os: ubuntu-latest, session: "mypy-3.6" }
          - { python-version: 3.8, os: ubuntu-latest, session: "tests-3.8" }
          - { python-version: 3.7, os: ubuntu-latest, session: "tests-3.7" }
          - { python-version: 3.6, os: ubuntu-latest, session: "tests-3.6" }
          - { python-version: 3.8, os: windows-latest, session: "tests-3.8" }
          - { python-version: 3.8, os: macos-latest, session: "tests-3.8" }
          - { python-version: 3.8, os: ubuntu-latest, session: "docs" }

    env:
      NOXSESSION: ${{ "${{ matrix.session }}" }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.1.1

      - name: Set up Python {{ "${{ matrix.python-version }}" }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ "${{ matrix.python-version }}" }}

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install Poetry
        run: |
          pip install --constraint=.github/workflows/constraints.txt poetry
          poetry --version

      - name: Install Nox
        run: |
          pip install --constraint=.github/workflows/constraints.txt nox
          nox --version

      - name: Run Nox
        run: |
          nox --force-color

      - name: Upload documentation
        if: matrix.session == 'docs'
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs/_build

      - name: Create coverage report
        if: always() && matrix.session == 'tests'
        run: |
          nox --force-color --session=coverage -- xml

      - name: Upload coverage report
        if: always() && matrix.session == 'tests'
        uses: codecov/codecov-action@v1.0.7
